//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLogs
    {
        public int RequestLogId { get; set; }
        public string UserName { get; set; }
        public string Controller { get; set; }
        public string ActionName { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
