//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int VentaId { get; set; }
        public int ProductoId { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
